### ISSUE TITLE
TARGET_JAVA_PACKAGE created incorrectly when auto generating config from lazybones archetype settings

### ISSUE THREAD

**Issue by reusr1** [headwirecom/aemdc#2]
in a lazybones project, when using aemdc config the TARGET_JAVA_PACKAGE is created incorrectly

in the stored-params.properties the setting is

slingModelsPackage=com.headwire.aem.base.models

referencing the models package, not the root java package for the project

suggestion: 

TARGET_JAVA_PACKAGE set to the parent package of slingModelsPackage
introduction of 
TARGET_JAVA_MODEL_PACKAGE set to slingModelsPackage

**Comment by mtstv** [comment]
Hi,
I am not sure that this parameter slingModelsPackage was defined only for models java subpackage in the Core project rolled by lazybones template.
In my lazybones project I defined the slingModelsPackage like "com.headwire.myaem.core" where there are 3 subpackages
com.headwire.myaem.core.models
com.headwire.myaem.core.services
com.headwire.myaem.core.servlets

**Comment by mtstv** [comment]
Fixed in release v0.10.1
- TARGET_JAVA_PACKAGE set to the parent package of slingModelsPackage
- TARGET_JAVA_MODEL_SUBPACKAGE added as param in the aemdc-config.properties
- Target folder in the model template type in the AEMDC Files project changed to 
TARGET_TYPE_FOLDER={{TARGET_JAVA_PACKAGE_FOLDER}}/{{TARGET_JAVA_MODEL_SUBPACKAGE}}
